server:
    port: 8081

spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/htc?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC&useSSL=false
        username: root
        password: 1234
    main:
        allow-circular-references: true


mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.htc.entity
    configuration:
        map-underscore-to-camel-case: true
